version: 2
registries:
  hex-organization-narrativeapp:
    type: hex-organization
    organization: narrativeapp
    key: "${{secrets.HEX_ORGANIZATION_NARRATIVEAPP_KEY}}"

updates:
- package-ecosystem: mix
  directory: "/"
  insecure-external-code-execution: allow
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  reviewers:
    - puzza007
    - narrative-donc
  registries:
    - hex-organization-narrativeapp
