version: 2
registries:
  hex-organization-narrativeapp:
    type: hex-organization
    organization: narrativeapp
    key: "${{secrets.HEX_ORGANIZATION_NARRATIVEAPP_KEY}}"

updates:
- package-ecosystem: mix
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  reviewers:
  - d-staehler
  - jimsynz
  - steffanlevet
  registries:
  - hex-organization-narrativeapp
